services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    container_name: bot
    restart: always
    environment:
      - DISCORD_DV_TOKEN=YOUR_DISCORD_BOT_TOKEN
      - DISCORD_DV_TEST_TOKEN=YOUR_DISCORD
      - DISCORD_DV_PREFIX=$
      - DISCORD_OWNER=YOUR_DISCORD_ID
      - REDIS_DV_URL=redis://rdb:6379
      - REDIS_USER=admin
      - REDIS_DV_PASSWD=admin
      - GCP_TOKEN=YOUR_GCP_TOKEN
      - GOOGLE_APPLICATION_CREDENTIALS="gcp-token.json"
      - AZURE_TTS_KEY=YOUR_AZURE_TTS_KEY
      - OPENAI_API_KEY=YOUR_OPENAI_API_KEY
      - TEST_ENV=false
      - DATABASE_URL=postgresql://pdb:5432/bot
      - DV_RSA_PUBLIC=YOUR_RSA_PUBLIC
      - DV_RSA_PRIVATE=YOUR_RSA_PRIVATE
    volumes:
      - ./src:/app
    depends_on:
      - db
    networks:
      - bot-network

  rdb:
    image: redis
    container_name: rdb
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - bot-network

  pdb:
    image: postgres
    container_name: pdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bot
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - bot-network